name: Coverage
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Lcov
      #      - name: show current status
      #        run: |
      #          ls -F
      - name: Upload coverage
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: lcov.info
